export const mapDept2Img = {
  'BME ': 'eng.png',
  BMES: 'nucl.png',
  'CHE ': 'eng.png',
  'CL  ': 'hss.png',
  'DMS ': 'life.png',
  ECON: 'ctm.png',
  'FL  ': 'hss.png',
  'GE  ': 'college.png',
  'GEC ': 'college.png',
  'HIS ': 'hss.png',
  'HSS ': 'hss.png',
  IEEM: 'eng.png',
  IPTH: 'college.png',
  'JMU ': 'art.png',
  'LS  ': 'life.png',
  'LST ': 'ctm.png',
  PHYS: 'science.png',
  STAT: 'science.png',
  'TE  ': 'ec.png',
  'TM  ': 'ctm.png',
  'WH  ': 'college.png',
  'WW  ': 'college.png',
  'WZ  ': 'college.png',
  'XA  ': 'college.png',
};

export const deptImages = [
  'art.png',
  'college.png',
  'ctm.png',
  'ec.png',
  'eecs.png',
  'eng.png',
  'hss.png',
  'life.png',
  'nucl.png',
  'science.png',
];
